eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    api-demo:
      path: /api-demo/**
      serviceId: service-demo
    web-demo:
      path: /web-demo/**
      serviceId: web-demo
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
